import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LivePreviewProvider } from "@/contexts/LivePreviewProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col items-start justify-start gap-8 bg-slate-950 text-slate-50 antialiased`}
        >
          <main className="max-h-1/2 max-w-1/2 flex flex-col items-start justify-start gap-8 m-auto">
            {children}
          </main>
        </body>
      </html>
      <LivePreviewProvider />
    </>
  );
}
